config/routes.rb
Rails.application.routes.draw do
  resources :custom_fields
  resources :contacts
  devise_for :users
  root to: 'home#index'  

end

app/models/combo_box_option.rb
class ComboBoxOption < ActiveRecord::Base
  belongs_to :custom_field
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_many :contact_custom_fields
  has_many :custom_fields, through: :contact_custom_fields
  accepts_nested_attributes_for :contact_custom_fields
end

app/models/contact_custom_field.rb
class ContactCustomField < ActiveRecord::Base
  belongs_to :contact
  belongs_to :custom_field
end

app/models/custom_field.rb
class CustomField < ActiveRecord::Base
  belongs_to :user
  has_many :combo_box_options
  has_many :contact_custom_fields
  accepts_nested_attributes_for :combo_box_options, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
  has_many :custom_fields
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.where(user_id: current_user.id)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.custom_fields = CustomField.where(user_id: current_user.id)
  end

  # GET /contacts/1/edit
  def edit
    @custom_fields = CustomField.where(user_id: current_user.id)
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:email, contact_custom_fields_attributes: [:value, :id, :custom_field_id, :custom_field]).merge(user_id: current_user.id)
    end
end

app/controllers/custom_fields_controller.rb
class CustomFieldsController < ApplicationController
  before_action :set_custom_field, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /custom_fields
  # GET /custom_fields.json
  def index
    @custom_fields = CustomField.where(user_id: current_user.id)
  end

  # GET /custom_fields/1
  # GET /custom_fields/1.json
  def show
  end

  # GET /custom_fields/new
  def new
    @custom_field = CustomField.new
  end

  # GET /custom_fields/1/edit
  def edit
  end

  # POST /custom_fields
  # POST /custom_fields.json
  def create
    @custom_field = CustomField.new(custom_field_params)

    respond_to do |format|
      if @custom_field.save
        format.html { redirect_to @custom_field, notice: 'Custom field was successfully created.' }
        format.json { render :show, status: :created, location: @custom_field }
      else
        format.html { render :new }
        format.json { render json: @custom_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_fields/1
  # PATCH/PUT /custom_fields/1.json
  def update
    respond_to do |format|
      if @custom_field.update(custom_field_params)
        format.html { redirect_to @custom_field, notice: 'Custom field was successfully updated.' }
        format.json { render :show, status: :ok, location: @custom_field }
      else
        format.html { render :edit }
        format.json { render json: @custom_field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_fields/1
  # DELETE /custom_fields/1.json
  def destroy
    @custom_field.destroy
    respond_to do |format|
      format.html { redirect_to custom_fields_url, notice: 'Custom field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_custom_field
      @custom_field = CustomField.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def custom_field_params
      params.require(:custom_field).permit(:name, :field_type, combo_box_options_attributes: [:name, :id, :_destroy]).merge(user_id: current_user.id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <%= f.fields_for :contact_custom_fields do |field| %>
    <div class="field">
      <%= field.label :value, field.object.custom_field.name %><br/>
      <% if field.object.custom_field.field_type == 'Text' %>
        <%= field.text_field :value %>
      <% elsif field.object.custom_field.field_type == 'Text field' %>
        <%= field.text_area :value %>
      <% else %>
        <%= field.select :value, field.object.custom_field.combo_box_options.map { |o| o.name } %>
      <% end %>
      <%= field.hidden_field :id %>
      <%= field.hidden_field :custom_field_id %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<% @contact.contact_custom_fields.each do |field| %>
  <p>
    <strong><%= field.custom_field.name %>:</strong>
    <%= field.value %>
  </p>
<% end %>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/custom_fields/_form.html.erb
<%= form_for(@custom_field, data: { 'ng-app' => 'FieldApp', 'ng-controller' => 'FieldController' }) do |f| %>
  <% if @custom_field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@custom_field.errors.count, "error") %> prohibited this custom_field from being saved:</h2>

      <ul>
      <% @custom_field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :field_type %><br>
    <%= f.select :field_type, ['Text', 'Text field', 'Combo Box'], {}, { data: { 'ng-model' => 'type', 'ng-init' => "type='#{@custom_field.field_type || 'Text'}';options=#{@custom_field.combo_box_options.to_json}" } } %>
  </div>
  <div data-ng-if="type==='Combo Box'">
    <div data-ng-repeat="option in options track by $index" class="field" data-ng-show="!options[$index]._destroy">
      <label for="custom_field_combo_box_options_attributes_{{$index}}_name">Name</label>
      <input type="text" data-ng-model="options[$index].name" name="custom_field[combo_box_options_attributes][{{$index}}][name]" id="custom_field_combo_box_options_attributes_{{$index}}_name" />
      <input type="hidden" data-ng-value="options[$index].id" name="custom_field[combo_box_options_attributes][{{$index}}][id]" id="custom_field_combo_box_options_attributes_{{$index}}_id" />
      <input type="hidden" data-ng-value="options[$index]._destroy" name="custom_field[combo_box_options_attributes][{{$index}}][_destroy]" id="custom_field_combo_box_options_attributes_{{$index}}__destroy" />
      <a data-ng-click="removeOption($index)">X</a>
    </div>
    <a data-ng-click="addOption()">Add option</a>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custom_fields/edit.html.erb
<h1>Editing Custom Field</h1>

<%= render 'form' %>

<%= link_to 'Show', @custom_field %> |
<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Custom Fields</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Field Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @custom_fields.each do |custom_field| %>
      <tr>
        <td><%= custom_field.name %></td>
        <td><%= custom_field.field_type %></td>
        <td><%= link_to 'Show', custom_field %></td>
        <td><%= link_to 'Edit', edit_custom_field_path(custom_field), data: { 'no-turbo-link' => '' } %></td>
        <td><%= link_to 'Destroy', custom_field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom field', new_custom_field_path, data: { 'no-turbo-link' => ''} %>

app/views/custom_fields/new.html.erb
<h1>New Custom Field</h1>

<%= render 'form' %>

<%= link_to 'Back', custom_fields_path %>

app/views/custom_fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @custom_field.name %>
</p>

<p>
  <strong>Field Type:</strong>
  <%= @custom_field.field_type %>
</p>

<p>
  <strong>Combo box options</strong>
  <% if @custom_field.field_type == 'Combo Box' %>
    <ul>
      <% @custom_field.combo_box_options.each do |o| %>
        <li><%= o.name %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_custom_field_path(@custom_field) %> |
<%= link_to 'Back', custom_fields_path %>

app/views/home/index.html.erb
<h1>Contacts app</h1>
<p><%= link_to 'Contacts', contacts_url %></p>
<p><%= link_to 'Custom fields', custom_fields_url %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesafioDev</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>